CREATE TABLE `users` ( `id` INT NOT NULL AUTO_INCREMENT , `username` CHAR(255) NOT NULL , `password` CHAR(255) NOT NULL , `signup_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `sessions` ( `started` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `expiry` INT NOT NULL DEFAULT '0' , `id` VARCHAR(32) NOT NULL , `user_id` INT NOT NULL ) ENGINE = InnoDB;
